services:
  dev:
    container_name: pypgstac
    build:
      context: .
      dockerfile: Dockerfile.pypgstac
    platform: linux/amd64
    depends_on:
      - database
    volumes:
      - ./:/opt/src
    environment:
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=database
      - PGDATABASE=postgis
  database:
    container_name: pgstac
    build:
      context: .
      dockerfile: Dockerfile.pgstac
    platform: linux/amd64
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=localhost
      - PGDATABASE=postgis
    ports:
      - "5439:5432"
    volumes:
      - pgstac-pgdata:/var/lib/postgresql/data
      - ./:/opt/src

volumes:
  pgstac-pgdata:
